### ISSUE TITLE
Script system error: VIET_events_old.txt

### ISSUE THREAD

**Issue by osccal** [cybrxkhan/VIET-Events-for-CK3#70]
I was trying out a multiplayer game with VIET enabled among a couple of mods. As the host I kept seeing instability that was not present in single player with several "not responding" messages before recovering. Eventually the game crashed, with the most likely culprit based on error.log being VIET

From what I can tell it's related to a specific section of VIET_events_old.txt:9606-9609. From what I can read from the event and log this is an event regarding a Chinese empress(VIETold.21379). At current I cannot pin down the cause. Will update as further investigation is done.  
[error.log](https://github.com/cybrxkhan/VIET-Events-for-CK3/files/6208166/error.log)
[debug.log](https://github.com/cybrxkhan/VIET-Events-for-CK3/files/6208173/debug.log)

**Comment by cybrxkhan** [comment]
Hello there, looks like that is a bug - but I'm not sure if it would be the cause of instability as it's a relatively minor thing (CK3 event code is remarkably resilient and doesn't crash anywhere as easily as CK2 which was a crash-fest even for the smallest of bugs at times). Not sure how I didn't catch that before either because I do look at the error logs when testing my mod. Anyways,  all that said, I've just fixed the bug (and discovered a different issue where for some reason the Github version of VIET did not have any of the new 1.3.1 event code) and uploaded the updated VIET_events_old_txt file to Github - feel free to download it and see if that helps.
